### ISSUE TITLE
add a new feature to share music from all plateforms

### ISSUE THREAD

**Issue by lukyyy9** [lukyyy9/Distant-Bot#3]
make /share returns spotify, deezer, yt music and apple music links when sharing a music from a platform

**Comment by lukyyy9** [comment]
do we need a new command ? or should we make an "omni" smart command?
maybe touchy bcs of yt links that can be shorts, videos or music

**Comment by Tonoplas909** [comment]
youtube shorts can be recognized if 'shorts' is 1st word after first '/' char
spotify is already supported by discord
need to see if possible

**Comment by lukyyy9** [comment]
@Tonoplas909 true but for the classic videos should we try anyway to request apis ?

**Comment by lukyyy9** [comment]
the point is to send other platforms links so everyone can listen to the music you shared
